# Extend the recommended Blitz config
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "blitz"

plugins:
  - "@typescript-eslint"

rules:
  import/prefer-default-export: error

  # Typescript type import should use "import type"
  "@typescript-eslint/consistent-type-imports": error
  "@typescript-eslint/no-unused-vars": error

  # Define import order rules
  import/order:
    - error
    - groups: [type, builtin, external, internal, parent, sibling, index, object]
      newlines-between: always
      pathGroupsExcludedImportTypes:
        - type
      pathGroups:
        - pattern: "+(react|blitz)"
          group: builtin
          position: before
        - pattern: "+(app|db|public|test)/**"
          group: internal
          position: before

overrides:
  - files: "**/*.test.ts"
    rules:
      "@typescript-eslint/no-explicit-any": "off"
